### PR TITLE
Change IOError to ArgumentError in ZGroup.jl

### LINKED ISSUE #199: Undefined error when trying to write to a non-writeable zgroup
The functions `zgroup` and `zcreate` to create a subgroup and subarray in a group attempt to throw an IOError if the group is not writeable, but `IOError` is not defined. (c.f. `Base.IOError` in the function `consolidate_metadata` which is defined). 

https://github.com/JuliaIO/Zarr.jl/blob/0a6cf35812e10475869795a385e4c744309ec899/src/ZGroup.jl#L149-L169

Example:
```julia
using Zarr
g = zgroup("test.zarr")
g = zopen("test.zarr")
zcreate(Float32, g, "foo", 5)
```
produces
```julia
ERROR: UndefVarError: `IOError` not defined in `Zarr`
Suggestion: check for spelling errors or missing imports.
Stacktrace:
 [1] zcreate(::Type{Float32}, g::ZGroup{DirectoryStore}, name::String, addargs::Int64; kwargs::@Kwargs{})
   @ Zarr ~/.julia/packages/Zarr/3QSdj/src/ZGroup.jl:151
 [2] zcreate(::Type{Float32}, g::ZGroup{DirectoryStore}, name::String, addargs::Int64)
   @ Zarr ~/.julia/packages/Zarr/3QSdj/src/ZGroup.jl:150
 [3] top-level scope
   @ REPL[13]:1
```

### PR DESCRIPTION
**Pull request by bwalker1**
Fixes #199

### CODE REVIEW

File: src/ZGroup.jl [hunk 1]
```diff
@@ -148,13 +148,13 @@ zgroup(s::String;kwargs...)=zgroup(storefromstring(s, true)...;kwargs...)
 
 "Create a subgroup of the group g"
 function zgroup(g::ZGroup, name; attrs=Dict()) 
-  g.writeable || throw(IOError("Zarr group is not writeable. Please re-open in write mode to create an array"))
+  g.writeable || throw(ArgumentError("Zarr group is not writeable. Please re-open in write mode to create an array"))
```
Comment (asinghvi17) [inline src/ZGroup.jl:151]:
```suggestion
  g.writeable || throw(ArgumentError("This Zarr group is not writeable. Please re-open in write mode to create an array"))
```

File: src/ZGroup.jl [hunk 2]
```diff
@@ -164,6 +164,6 @@ end
 HTTP.serve(s::Union{ZArray,ZGroup}, args...; kwargs...) = HTTP.serve(s.storage, s.path, args...; kwargs...)
 writezip(io::IO, s::Union{ZArray,ZGroup}; kwargs...) = writezip(io, s.storage, s.path; kwargs...)
 function consolidate_metadata(z::Union{ZArray,ZGroup}) 
-  z.writeable || throw(Base.IOError("Zarr group is not writeable. Please re-open in write mode to create an array",0))
+  z.writeable || throw(ArgumentError("Zarr group is not writeable. Please re-open in write mode to create an array"))
```
Comment (asinghvi17) [inline src/ZGroup.jl:167]:
```suggestion
  z.writeable || throw(ArgumentError("This Zarr group is not writeable. Please re-open in write mode to create an array"))
```
